require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/themes", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Theme. As you add validations to Theme, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ThemesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Theme.create! valid_attributes
      get themes_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      theme = Theme.create! valid_attributes
      get theme_url(theme), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Theme" do
        expect {
          post themes_url,
               params: { theme: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Theme, :count).by(1)
      end

      it "renders a JSON response with the new theme" do
        post themes_url,
             params: { theme: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Theme" do
        expect {
          post themes_url,
               params: { theme: invalid_attributes }, as: :json
        }.to change(Theme, :count).by(0)
      end

      it "renders a JSON response with errors for the new theme" do
        post themes_url,
             params: { theme: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested theme" do
        theme = Theme.create! valid_attributes
        patch theme_url(theme),
              params: { theme: new_attributes }, headers: valid_headers, as: :json
        theme.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the theme" do
        theme = Theme.create! valid_attributes
        patch theme_url(theme),
              params: { theme: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the theme" do
        theme = Theme.create! valid_attributes
        patch theme_url(theme),
              params: { theme: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested theme" do
      theme = Theme.create! valid_attributes
      expect {
        delete theme_url(theme), headers: valid_headers, as: :json
      }.to change(Theme, :count).by(-1)
    end
  end
end
